services:
# frontend container part
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    networks:
      - mern    
  
# for backend
  server:
    build: ./server
    ports:
      - "5050:5000"
    env_file:
      - ./server/.env
    networks:
      - mern

  
networks:
  mern:
    driver: bridge

